init:
  - git config --global core.autocrlf input
#  - ps: iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))

build:
  verbosity: detailed

# Test against this version of Node.js
environment:
  nodejs_version: "4.6"

# Install scripts. (runs after repo cloning)
install:
  # Get the latest stable version of Node.js or io.js
  - ps: Install-Product node $env:nodejs_version
  # install modules
  - cd src/Fable.Import.SharePoint
  - call npm install  
  - cd ../..
  
os: Visual Studio 2015
before_build:
  - cmd: set PATH=C:\Program Files (x86)\MSBuild\14.0\Bin;%PATH%
build_script:
  - cmd: build.cmd
test: off
version: 0.0.1.{build}

#on_finish:
#  - ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))